quotes/apps/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path("<int:page>", views.main, name="root_paginate"),
    path("description/<int:author_id>/", views.about, name="description"),
    path("tags/<str:tag_name>", views.authors_by_tags, name="tags"),
    path("author/add/", views.AuthorView.as_view(), name="add_author"),
    path("quote/add/", views.QuoteView.as_view(), name="add_quote"),
    path("tag/add/", views.TagView.as_view(), name="add_tag"),
]

quotes/apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/"  , RegisterView.as_view(), name="signup"),
    path("signin/"  , LoginView.as_view(template_name="users/signin.html", authentication_form=LoginForm, redirect_authenticated_user=True, ), name="signin", ),
    path("signout/" , LogoutView.as_view(template_name="users/signout.html"), name="signout"),

    path("reset-password/", ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/'   , admin.site.urls),
    path(""         , include("apps.quotes.urls")),
    path("users/"   , include("apps.users.urls")),
]

quotes/apps/quotes/models.py
from typing import Any
from django.db import models
# from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.db.models import Model

# Create your models here.

class UserField(models.ForeignKey):

    # def clean(self, value: Any, model_instance: Model | None) -> Any:
    #      return super().clean(value, model_instance)
    
    def pre_save(self, model_instance, add):
        if add:
            value = getattr(model_instance, self.attname)
            if value is None:
                 value = 1 # User with pk=1 is "admin"
            return value
        else:
            value = getattr(model_instance, self.attname)
            if value is None:
                 model_instance.refresh_from_db(fields=[self.attname]) # Restore old value
            return super().pre_save(model_instance, add)
        
class Logger(models.Model):
    created_by    = UserField(User, to_field="id" , on_delete=models.CASCADE, null=False, related_name="%(app_label)s_%(class)s_created_by",)# default=User.objects.get(pk=1))
    modified_by   = UserField(User, to_field="id" , on_delete=models.CASCADE, null=False, related_name="%(app_label)s_%(class)s_modified_by",)# default=User.objects.get(pk=1))
    created_at    = models.DateTimeField(null=False, auto_now_add =True)
    modified_at   = models.DateTimeField(null=False, auto_now     =True)

    class Meta:
            abstract = True
    
class Author(Logger):
    fullname        = models.CharField(max_length=256, null=False, unique=True)
    born_date       = models.DateField(null=False,)
    born_location   = models.CharField(max_length=1024, null=False)
    description     = models.TextField(null=False)

    def __str__(self):
            return f"{self.fullname}"

class Tag(Logger):
    name = models.CharField(max_length=256, null=False, unique=True)
    
    def __str__(self):
            return f"{self.name}"

class Quote(Logger):
    quote   = models.TextField(null=False, unique=True)
    # tags    = ArrayField(models.CharField(max_length=256, null=False, unique=True))
    tags = models.ManyToManyField(Tag)

    author = models.ForeignKey(Author, on_delete=models.CASCADE)#, related_name="author_id")
    def __str__(self):
            return f"{self.quote}"


# class Tags(models.Model):
#     tag     = models.ForeignKey(Tag     , on_delete=models.CASCADE)
#     quote   = models.ForeignKey(Quote   , on_delete=models.CASCADE)
#     # name = models.CharField(max_length=32, null=False, unique=True)
#     pass

quotes/apps/quotes/forms.py
from django.forms import (
    ModelForm,
    CharField,
    TextInput,
    ModelChoiceField,
    ModelMultipleChoiceField,
    CheckboxSelectMultiple,
)
from .models import Tag, Author, Quote


class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = ["name"]


class QuoteForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.all())
    tags = ModelMultipleChoiceField(
        queryset=Tag.objects.all().order_by("name"), widget=CheckboxSelectMultiple
    )

    class Meta:
        model = Quote
        fields = ["quote", "author", "tags"]


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]

quotes/apps/quotes/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, redirect
from django.views import View

from .forms import AuthorForm, QuoteForm, TagForm
from .models import Author, Tag, Quote

# Create your views here.
def main(request, page=1):
    tags = Tag.objects.annotate(num_quotes=Count("quote")).order_by("-num_quotes").all()[:10]

    quotes = (
        Quote.objects.select_related("author")
        .prefetch_related("tags")
        .all()
        .order_by("created_at")
    )
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page, "tags": tags})

def about(request, author_id):
    description = Author.objects.filter(pk=author_id)
    return render(request, "quotes/description.html", context={"authors": description})

def authors_by_tags(request, tag_name):
    tags = Tag.objects.filter(name=tag_name).first()
    quotes = tags.quote_set.all()
    return render(request, "quotes/tags.html", context={"quotes": quotes})


class AuthorView(View):

    template_name = "quotes/add_author.html"
    form_class = AuthorForm
    model = Author

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.created_by  = request.user
            instance.modified_by = request.user
            form.save()
            return redirect(to="quotes:main")

        return render(request, self.template_name, {"form": form})


class QuoteView(View):
    template_name = "quotes/add_quote.html"
    form_class = QuoteForm
    model = Quote

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):

        form = self.form_class(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.created_by  = request.user
            instance.modified_by = request.user
            form.save()
            return redirect(to="quotes:main")

        return render(request, self.template_name, {"form": form})

class TagView(View):
    template_name = "quotes/add_tag.html"
    form_class = TagForm
    model = Tag

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):

        form = self.form_class(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.created_by  = request.user
            instance.modified_by = request.user
            form.save()
            return redirect(to="quotes:main")

        return render(request, self.template_name, {"form": form})

quotes/apps/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
    <form method="POST" action="{% url 'quotes:add_author' %}">
        {% csrf_token %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <p> {{ error }} </p>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <div class="form-row">
            <div class="mb-3">
                <div class="form-label">
                    <label class="form-label">
                        Author full name: {{ form.fullname }}
                    </label>
                    <span>{{ form.errors.fullname }}</span>
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="mb-3">
                <div class="form-label">
                    <label class="form-label">
                        Born date: {{ form.born_date }}
                    </label>
                    <span>{{ form.errors.born_date }}</span>
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="mb-3">
                <div class="form-label">
                    <label class="form-label">
                        Born location: {{ form.born_location }}
                    </label>
                    <span>{{ form.errors.born_location }}</span>
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="mb-3">
                <div class="form-label">
                    <label class="form-label">
                        Description: {{ form.description }}
                    </label>
                    <span>{{ form.errors.description }}</span>
                </div>
            </div>
        </div>

        <div class="form-label">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>
{% endblock %}

quotes/apps/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <p> {{ error }} </p>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <div class="form-row">
            <div class="form-label">
                <label class="form-label"> Author: </label>
                <div class="form-group">{{ form.author }}</div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-label">
                <label class="form-label"> Quote: </label>
                <div class="form-group">{{ form.quote }}</div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-label">
                <label class="form-label"> Tags: </label>
                 <p>{% for tag in form.tags %}
                     {{ tag }}
                {% endfor %}</p>
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

quotes/apps/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <p> {{ error }} </p>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <div class="form-row">
            <div class="form-label">
                <label class="form-label"> Name: </label>
                <div class="form-group">{{ form.name }}</div>
            </div>
        </div>


        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

<div class="form-row">
    <div class="form-label">
        <label class="form-label"> Tags: </label>
         <p>{% for tag in form.tags %}
             {{ tag }}
        {% endfor %}</p>
    </div>
</div>

{{form.non_field_errors}}
{{form.errors}}
{{error_message}}

quotes/apps/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static '/quotes/quotes.css' %}">
    <title>Homework 10</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
        </div>

    {% block content %} {% endblock %}
    </div>
</body>
</html>

quotes/apps/quotes/templates/quotes/description.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="author-details">
        {% for el in authors %}
        <h3 class="author-title">
            {{el.fullname}}
        </h3>
        <p><strong>Born:</strong> <span class="author-born-date">{{el.born_date}}</span> <span
                class="author-born-location">{{el.born_location}}</span>
        </p>
        <p><strong>Description:</strong></p>
        <div class="author-description">{{el.description}}</div>
        {% endfor %}
</div>

{% endblock %}

quotes/apps/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="row">

    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a href="{% url 'quotes:description' author_id=quote.author_id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tags' tag_name=tag %}">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="first">
                    <a class="{% if quotes.num_pages == 0 %} disabled {% endif %}"
                            href="{% url 'quotes:root_paginate' 1 %}">
                        <span aria-hidden="true">↑</span> First
                    </a>
                </li>
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                            href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>

                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                            href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span>
                    </a>
                </li>
                <li class="last">
                    <a class="{% if quotes.num_pages == 0 %} disabled {% endif %}"
                            href="{% url 'quotes:root_paginate' quotes.paginator.num_pages %}">
                        <span aria-hidden="true">↓</span> Last
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="col-md-4 tags-box">
        <h2>Top Ten tags</h2>
        {% for tag in tags %}
            <span class="tag-item">
                <a class="tag" style="font-size: 28px" href="{% url 'quotes:tags' tag_name=tag %}">{{ tag }}</a>
            </span><br>
        {% endfor %}
    <div class="col-md-4">
        {% if user.is_authenticated %}
            <div><a href="{% url 'users:signout' %}" class="btn btn-primary">Signout</a></div><br>
            <div><a href="{% url 'quotes:add_author' %}"class="btn btn-primary">Add author</a></div><br>
            <div><a href="{% url 'quotes:add_quote' %}"class="btn btn-primary">Add quote</a></div><br>
            <div><a href="{% url 'quotes:add_tag' %}"class="btn btn-primary">Add tag</a></div><br>
        {% else %}
            <div><a href="{% url 'users:signup' %}" class="btn btn-primary">Signup</a></div><br>
            <div><a href="{% url 'users:signin' %}" class="btn btn-primary">Signin</a></div><br>
        {% endif %}
    </div>
{% endblock %}

quotes/apps/quotes/templates/quotes/tags.html
{% extends 'quotes/base.html' %}

{% block content %}

{% for quote in quotes %},
<div class="row">
    <div class="col-md-8">
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quotes:description' author_id=quote.author_id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tags' tag_name=tag %}">{{tag}}</a>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
{% endfor %}
{% endblock %}